image: gitpod/workspace-full-vnc

ports:
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: open-browser
    visibility: public

tasks:
- name: install mamba
  init: |
    cd /workspace
    curl -L -O "https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-$(uname)-$(uname -m).sh"
    bash Mambaforge-$(uname)-$(uname -m).sh -b -p /workspace/conda && rm Mambaforge-$(uname)-$(uname -m).sh
    /workspace/conda/bin/mamba init bash

    source ${HOME}/.bashrc

    mamba create -n minigraph -c bioconda -c conda-forge blast minigraph qt -y

    wget https://github.com/rrwick/Bandage/releases/download/v0.8.1/Bandage_Ubuntu_dynamic_v0_8_1.zip
    unzip Bandage_Ubuntu_dynamic_v0_8_1.zip

    wget https://raw.githubusercontent.com/cistarsa/BGA-23_MTomics/main/MTranscripts.mfa
    wget https://sk13.cog.sanger.ac.uk/D02_files.tgz
    tar xzf D02_files.tgz
    wget https://sk13.cog.sanger.ac.uk/D11_files.tgz
    tar xzf D11_files.tgz

  command: |
    /workspace/conda/bin/mamba init bash
    source ${HOME}/.bashrc
    mamba activate minigraph

    git clone https://github.com/lh3/minigraph.git

    export LD_LIBRARY_PATH=/workspace/conda/envs/minigraph/lib/:$LD_LIBRARY_PATH
    clear
    
vscode:
  extensions:
    - anwar.papyrus-pdf

workspaceLocation: "/workspace"

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to true)
    addComment: true
    # add a "Review in Gitpod" button to pull requests (defaults to false)
    addBadge: false
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: prebuilt-in-gitpod
